-- ================================================================
-- Jonogon News - 132 Master Categories Database Seed SQL
-- Database: janogon_db / jonogonn_news_db
-- Table: categories
-- ================================================================

-- 1. Recreate Clean Categories Table
DROP TABLE IF EXISTS `categories`;

CREATE TABLE `categories` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(150) NOT NULL,
    `name_bn` VARCHAR(150) NULL,
    `name_en` VARCHAR(150) NULL,
    `slug` VARCHAR(100) NOT NULL UNIQUE,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Insert All 132 Categories (with Bangla & English names)
INSERT INTO `categories` (`name`, `name_bn`, `name_en`, `slug`) VALUES
('সর্বশেষ', 'সর্বশেষ', 'Latest', 'latest'),
('জাতীয়', 'জাতীয়', 'National', 'national'),
('বাংলাদেশ', 'বাংলাদেশ', 'Bangladesh', 'bangladesh'),
('প্রবাসী', 'প্রবাসী', 'Expatriates', 'probashi'),
('রাজধানী', 'রাজধানী', 'Capital', 'capital'),
('সারাদেশ', 'সারাদেশ', 'Countrywide', 'saradesh'),
('জেলা সংবাদ', 'জেলা সংবাদ', 'District News', 'district-news'),
('রাজনীতি', 'রাজনীতি', 'Politics', 'politics'),
('নির্বাচন', 'নির্বাচন', 'Election', 'election'),
('আইন-আদালত', 'আইন-আদালত', 'Law & Court', 'law-court'),
('অপরাধ', 'অপরাধ', 'Crime', 'crime'),
('প্রশাসন', 'প্রশাসন', 'Administration', 'administration'),
('সরকার', 'সরকার', 'Government', 'government'),
('সংসদ', 'সংসদ', 'Parliament', 'parliament'),
('কূটনীতি', 'কূটনীতি', 'Diplomacy', 'diplomacy'),
('আন্তর্জাতিক', 'আন্তর্জাতিক', 'International', 'international'),
('বিশ্ব', 'বিশ্ব', 'World', 'world'),
('ভারত', 'ভারত', 'India', 'india'),
('পাকিস্তান', 'পাকিস্তান', 'Pakistan', 'pakistan'),
('চীন', 'চীন', 'China', 'china'),
('মধ্যপ্রাচ্য', 'মধ্যপ্রাচ্য', 'Middle East', 'middle-east'),
('এশিয়া', 'এশিয়া', 'Asia', 'asia'),
('ইউরোপ', 'ইউরোপ', 'Europe', 'europe'),
('আমেরিকা', 'আমেরিকা', 'America', 'america'),
('আফ্রিকা', 'আফ্রিকা', 'Africa', 'africa'),
('লাতিন আমেরিকা', 'লাতিন আমেরিকা', 'Latin America', 'latin-america'),
('প্রতিবেশী দেশ', 'প্রতিবেশী দেশ', 'Neighboring Countries', 'neighbor-countries'),
('বাণিজ্য', 'বাণিজ্য', 'Trade', 'trade'),
('ব্যবসা', 'ব্যবসা', 'Business', 'business'),
('অর্থনীতি', 'অর্থনীতি', 'Economy', 'economy'),
('শেয়ারবাজার', 'শেয়ারবাজার', 'Stock Market', 'stock-market'),
('ব্যাংক', 'ব্যাংক', 'Banking', 'bank'),
('শিল্প', 'শিল্প', 'Industry', 'industry'),
('করপোরেট', 'করপোরেট', 'Corporate', 'corporate'),
('বিশ্ববাণিজ্য', 'বিশ্ববাণিজ্য', 'Global Trade', 'world-trade'),
('আপনার টাকা', 'আপনার টাকা', 'Your Money', 'your-money'),
('উদ্যোক্তা', 'উদ্যোক্তা', 'Entrepreneur', 'entrepreneur'),
('চাকরি', 'চাকরি', 'Jobs', 'jobs'),
('নিয়োগ', 'নিয়োগ', 'Recruitment', 'recruitment'),
('ক্যারিয়ার', 'ক্যারিয়ার', 'Career', 'career'),
('শিক্ষা', 'শিক্ষা', 'Education', 'education'),
('ভর্তি', 'ভর্তি', 'Admission', 'admission'),
('পরীক্ষা', 'পরীক্ষা', 'Exam', 'exam'),
('বৃত্তি', 'বৃত্তি', 'Scholarship', 'scholarship'),
('উচ্চশিক্ষা', 'উচ্চশিক্ষা', 'Higher Education', 'higher-education'),
('ক্যাম্পাস', 'ক্যাম্পাস', 'Campus', 'campus'),
('বিজ্ঞান', 'বিজ্ঞান', 'Science', 'science'),
('প্রযুক্তি', 'প্রযুক্তি', 'Technology', 'tech'),
('গ্যাজেট', 'গ্যাজেট', 'Gadgets', 'gadgets'),
('টিপস', 'টিপস', 'Tips', 'tips'),
('অটোমোবাইল', 'অটোমোবাইল', 'Automobile', 'automobile'),
('সাইবার জগৎ', 'সাইবার জগৎ', 'Cyber World', 'cyber-world'),
('ফ্রিল্যান্সিং', 'ফ্রিল্যান্সিং', 'Freelancing', 'freelancing'),
('কৃত্রিম বুদ্ধিমত্তা', 'কৃত্রিম বুদ্ধিমত্তা', 'AI & Machine Learning', 'ai'),
('এভিয়েশন', 'এভিয়েশন', 'Aviation', 'aviation'),
('স্বাস্থ্য', 'স্বাস্থ্য', 'Health', 'health'),
('পরিবেশ', 'পরিবেশ', 'Environment', 'environment'),
('জলবায়ু', 'জলবায়ু', 'Climate', 'climate'),
('কৃষি', 'কৃষি', 'Agriculture', 'agriculture'),
('ধর্ম', 'ধর্ম', 'Religion', 'religion'),
('ইসলাম', 'ইসলাম', 'Islam', 'islam'),
('সনাতন', 'সনাতন', 'Sanatan', 'sanatan'),
('বৌদ্ধ', 'বৌদ্ধ', 'Buddhism', 'buddhist'),
('খ্রিষ্টান', 'খ্রিষ্টান', 'Christianity', 'christian'),
('খেলা', 'খেলা', 'Sports', 'sports'),
('ক্রিকেট', 'ক্রিকেট', 'Cricket', 'cricket'),
('ফুটবল', 'ফুটবল', 'Football', 'football'),
('টেনিস', 'টেনিস', 'Tennis', 'tennis'),
('অন্যান্য খেলা', 'অন্যান্য খেলা', 'Other Sports', 'other-sports'),
('বিনোদন', 'বিনোদন', 'Entertainment', 'entertainment'),
('টেলিভিশন', 'টেলিভিশন', 'Television', 'television'),
('ওটিটি', 'ওটিটি', 'OTT', 'ott'),
('সিনেমা', 'সিনেমা', 'Cinema', 'cinema'),
('হলিউড', 'হলিউড', 'Hollywood', 'hollywood'),
('বলিউড', 'বলিউড', 'Bollywood', 'bollywood'),
('টলিউড', 'টলিউড', 'Tollywood', 'tollywood'),
('গান', 'গান', 'Music', 'music'),
('নাটক', 'নাটক', 'Drama', 'drama'),
('জীবনযাপন', 'জীবনযাপন', 'Lifestyle', 'lifestyle'),
('ভ্রমণ', 'ভ্রমণ', 'Travel', 'travel'),
('পর্যটন', 'পর্যটন', 'Tourism', 'tourism'),
('সম্পর্ক', 'সম্পর্ক', 'Relationship', 'relationship'),
('সুস্থতা', 'সুস্থতা', 'Wellness', 'wellness'),
('রাশিফল', 'রাশিফল', 'Horoscope', 'horoscope'),
('ফ্যাশন', 'ফ্যাশন', 'Fashion', 'fashion'),
('স্টাইল', 'স্টাইল', 'Style', 'style'),
('রূপচর্চা', 'রূপচর্চা', 'Beauty Care', 'beauty'),
('গৃহসজ্জা', 'গৃহসজ্জা', 'Home Decor', 'home-decor'),
('কেনাকাটা', 'কেনাকাটা', 'Shopping', 'shopping'),
('নারী ও শিশু', 'নারী ও শিশু', 'Women & Child', 'women-child'),
('প্রবাস', 'প্রবাস', 'Expatriate', 'probash'),
('শিল্প-সাহিত্য', 'শিল্প-সাহিত্য', 'Art & Literature', 'art-literature'),
('সাহিত্য', 'সাহিত্য', 'Literature', 'literature'),
('কবিতা', 'কবিতা', 'Poetry', 'poetry'),
('গল্প', 'গল্প', 'Story', 'story'),
('বই', 'বই', 'Books', 'books'),
('সংস্কৃতি', 'সংস্কৃতি', 'Culture', 'culture'),
('মতামত', 'মতামত', 'Opinion', 'opinion'),
('সম্পাদকীয়', 'সম্পাদকীয়', 'Editorial', 'editorial'),
('কলাম', 'কলাম', 'Column', 'column'),
('সাক্ষাৎকার', 'সাক্ষাৎকার', 'Interview', 'interview'),
('বিশ্লেষণ', 'বিশ্লেষণ', 'Analysis', 'analysis'),
('ফিচার', 'ফিচার', 'Feature', 'feature'),
('বিশেষ প্রতিবেদন', 'বিশেষ প্রতিবেদন', 'Special Report', 'special-report'),
('দীর্ঘপাঠ', 'দীর্ঘপাঠ', 'Long Read', 'long-read'),
('মানবিক গল্প', 'মানবিক গল্প', 'Human Story', 'human-story'),
('ইতিহাস', 'ইতিহাস', 'History', 'history'),
('১৯৭১', '১৯৭১', '1971', '1971'),
('অর্জন', 'অর্জন', 'Achievement', 'achievement'),
('সমাজ', 'সমাজ', 'Society', 'society'),
('মানুষ', 'মানুষ', 'People', 'people'),
('মিডিয়া', 'মিডিয়া', 'Media', 'media'),
('সোশ্যাল মিডিয়া', 'সোশ্যাল মিডিয়া', 'Social Media', 'social-media'),
('বিচিত্র', 'বিচিত্র', 'Curiosities', 'curiosities'),
('জীবনকাহিনি', 'জীবনকাহিনি', 'Life Stories', 'biography'),
('ছবি', 'ছবি', 'Photos', 'photos'),
('ফটো স্টোরি', 'ফটো স্টোরি', 'Photo Story', 'photo-story'),
('ফটোগ্যালারি', 'ফটোগ্যালারি', 'Photo Gallery', 'photo-gallery'),
('ভিডিও', 'ভিডিও', 'Video', 'video'),
('ভিডিও স্টোরি', 'ভিডিও স্টোরি', 'Video Story', 'video-story'),
('ভিডিও গ্যালারি', 'ভিডিও গ্যালারি', 'Video Gallery', 'video-gallery'),
('অডিও', 'অডিও', 'Audio', 'audio'),
('পডকাস্ট', 'পডকাস্ট', 'Podcast', 'podcast'),
('লাইভ', 'লাইভ', 'Live', 'live'),
('সংবাদ বিশ্লেষণ', 'সংবাদ বিশ্লেষণ', 'News Analysis', 'news-analysis'),
('অনুসন্ধানী প্রতিবেদন', 'অনুসন্ধানী প্রতিবেদন', 'Investigative Report', 'investigative'),
('বিশেষ সংখ্যা', 'বিশেষ সংখ্যা', 'Special Edition', 'special-edition'),
('ম্যাগাজিন', 'ম্যাগাজিন', 'Magazine', 'magazine'),
('ই-পেপার', 'ই-পেপার', 'E-Paper', 'e-paper'),
('বিজ্ঞাপন', 'বিজ্ঞাপন', 'Advertisement', 'advertisement'),
('অ্যাডভার্টোরিয়াল', 'অ্যাডভার্টোরিয়াল', 'Advertorial', 'advertorial');
